Repository vaticle/typedb-client-nodejs, pull requests merged in 2019-09, with the labels that each got.

#54 Add title to GitHub Release
  BUILD
Labels: build, feature

#55 Adapt to latest @graknlabs_bazel_distribution
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: build

#56 Use release-validate-deps to ensure that client-nodejs depends on a released version of protocol
  .circleci/config.yml
Labels: build

#57 Fix bazel build strategies
  .bazelrc
Labels: bug, build

#58 Upgrade @graknlabs_build_tools to fix CI
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build
