Repository vaticle/typedb-client-nodejs, pull requests merged in 2019-10, with the labels that each got.

#59 Refactor how version is provided to deployment rule
  .circleci/config.yml
  BUILD
  dependencies/graknlabs/dependencies.bzl
Labels: build, refactor

#64 Closes the transaction on GrpcCommunicator error
  .circleci/config.yml
  BUILD
  package.json
  src/service/Session/util/GrpcCommunicator.js
  tests/service/session/transaction/GraknTx.test.js
  tests/support/GraknTestEnvironment.js
  yarn.lock
Labels: bug

#66 Provides a function for checking if transaction is open
  src/Transaction.js
  src/service/Session/TransactionService.js
  tests/service/session/transaction/GraknTx.test.js
Labels: feature

#68 Delete Queries return Void Answer Type
  BUILD
  dependencies/graknlabs/dependencies.bzl
  src/service/Session/util/AnswerFactory.js
  tests/service/session/transaction/Query.test.js
Labels: refactor

#69 isDeleted() is added to Concept
  src/service/Session/concept/Methods.js
  tests/service/session/transaction/Concept.test.js
Labels: feature

#70 Temporarily fixes CI on master
  .circleci/config.yml
Labels: build

#73 Reverts: Delete Queries return Void Answer Type
  .circleci/config.yml
  BUILD
  src/service/Session/util/AnswerFactory.js
  tests/service/session/transaction/Query.test.js
Labels: build

#75 Temporarily fixes CI on master
  .circleci/config.yml
Labels: build

#76 Remove the release-validate job from the release workflow
  .circleci/config.yml
Labels: build

#77 close() on transaction checks if transaction is already closed
  src/service/Session/util/GrpcCommunicator.js
  tests/service/session/transaction/GraknTx.test.js
Labels: bug

#79 Handle error received without client request
  src/service/Session/util/GrpcCommunicator.js
Labels: bug
