Repository vaticle/typedb-client-nodejs, pull requests merged in 2019-03, with the labels that each got.

#17 Add grabl-marker for autoupdating
  WORKSPACE
Labels: build

#18 Add CI pipeline for releasing
  .circleci/config.yml
  WORKSPACE
Labels: build

#23 Rename grakn-core-all-linux.tar.gz
  .circleci/config.yml
Labels: bug, build

#24 Update npm version on circle machine
  .circleci/config.yml
  tests/deployment/application.test.js
Labels: bug

#25 Finalize test deployment
  .circleci/config.yml
  tests/deployment/application.test.js
Labels: bug

#26 Finalize test deployment
  .circleci/config.yml
  tests/deployment/application.test.js
Labels: bug

#34 Add benchmark as transitive dependency
  WORKSPACE
Labels: bug

#35 Release pipeline for client-nodejs
  .circleci/config.yml
  BUILD
  RELEASE_TEMPLATE.md
  WORKSPACE
  deployment.properties
Labels: build, feature
