Repository vaticle/typedb-client-nodejs, pull requests merged in 2020-12, with the labels that each got.

#112 Update README
  README.md
Labels: priority: low, type: documentation

#114 Fix dependency-analysis by adjusting indentation
  .grabl/automation.yml
Labels: priority: blocker, type: bug, type: build

#116 Add pulse to RPCSession
  package-lock.json
  package.json
  rpc/RPCSession.ts
Labels: priority: high, type: bug

#119 Fix errors being swallowed + update protocol
  BUILD
  common/ProtoBuilder.ts
  concept/ConceptManager.ts
  concept/LogicManager.ts
  concept/answer/Answer.ts
  concept/answer/AnswerGroup.ts
  concept/answer/ConceptMap.ts
  concept/logic/impl/RuleImpl.ts
  concept/proto/ConceptProtoBuilder.ts
  concept/proto/ConceptProtoReader.ts
  concept/thing/impl/AttributeImpl.ts
  concept/thing/impl/EntityImpl.ts
  concept/thing/impl/RelationImpl.ts
  concept/thing/impl/ThingImpl.ts
  concept/type/AttributeType.ts
  concept/type/impl/AttributeTypeImpl.ts
  concept/type/impl/EntityTypeImpl.ts
  concept/type/impl/RelationTypeImpl.ts
  concept/type/impl/RoleTypeImpl.ts
  concept/type/impl/ThingTypeImpl.ts
  concept/type/impl/TypeImpl.ts
  dependencies_internal.ts
  package-lock.json
  package.json
  query/QueryManager.ts
  rpc/GraknClient.ts
  rpc/RPCDatabaseManager.ts
  rpc/RPCSession.ts
  rpc/RPCTransaction.ts
  rpc/Stream.ts
Labels: priority: low, type: bug

#121 Update protocol: repeated fields now pluralised
  concept/thing/impl/AttributeImpl.ts
  concept/thing/impl/RelationImpl.ts
  concept/thing/impl/ThingImpl.ts
  concept/type/impl/AttributeTypeImpl.ts
  concept/type/impl/RelationTypeImpl.ts
  concept/type/impl/RoleTypeImpl.ts
  concept/type/impl/ThingTypeImpl.ts
  concept/type/impl/TypeImpl.ts
  package-lock.json
  package.json
  query/QueryManager.ts
Labels: priority: low, type: refactor

#123 Fix Attribute.GetOwners with no parameter
  concept/thing/Attribute.ts
  concept/thing/impl/AttributeImpl.ts
  concept/thing/impl/RelationImpl.ts
  concept/thing/impl/ThingImpl.ts
  concept/type/impl/AttributeTypeImpl.ts
  concept/type/impl/RelationTypeImpl.ts
  concept/type/impl/ThingTypeImpl.ts
Labels: priority: low, type: bug

#124 Fix GetPlayersByRoleType having 'duplicate' keys
  concept/thing/impl/RelationImpl.ts
Labels: priority: low, type: bug

#125 Byte hex string conversions
  common/Bytes.ts
  concept/ConceptManager.ts
  concept/proto/ConceptProtoBuilder.ts
  concept/thing/impl/AttributeImpl.ts
  concept/thing/impl/EntityImpl.ts
  concept/thing/impl/RelationImpl.ts
  concept/thing/impl/ThingImpl.ts
  concept/type/impl/AttributeTypeImpl.ts
  dependencies_internal.ts
Labels: type: bug

#126 Remove leftover TODOs related to hex string conversions
  concept/thing/impl/AttributeImpl.ts
  concept/thing/impl/EntityImpl.ts
  concept/type/impl/AttributeTypeImpl.ts
Labels: type: refactor

#128 Protocol Synchronisation
  concept/ConceptManager.ts
  concept/type/AttributeType.ts
  concept/type/EntityType.ts
  concept/type/RelationType.ts
  concept/type/Type.ts
  concept/type/impl/AttributeTypeImpl.ts
  concept/type/impl/EntityTypeImpl.ts
  concept/type/impl/RelationTypeImpl.ts
  concept/type/impl/ThingTypeImpl.ts
  concept/type/impl/TypeImpl.ts
  package-lock.json
  package.json
  rpc/RPCSession.ts
Labels: type: feature

#129 Validate the dependency declaration correctness before releasing
  .grabl/automation.yml
  BUILD
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#130 Adapt to new grabl
  .grabl/automation.yml
Labels: priority: high, type: build, type: refactor

#132 Change code owner to Alistair
  .github/CODEOWNERS
Labels: type: build
