Repository vaticle/typedb-client-nodejs, pull requests merged in 2020-06, with the labels that each got.

#96 Upgrade various graknlabs dependencies and grpc 1.24.3
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  package.json
  yarn.lock
Labels: priority: high

#98 Overhaul query options
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  src/service/Session/TransactionService.js
  src/service/Session/util/RequestBuilder.js
  tests/service/session/transaction/CommitTx.test.js
  tests/service/session/transaction/GraknTx.test.js
  tests/service/session/transaction/Query.test.js
Labels: priority: high, type: feature

#100 Update CI image to Ubuntu 16 and bump Build Tools
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: type: build
