Repository vaticle/typedb-client-nodejs, pull requests merged in 2021-01, with the labels that each got.

#134 Update usage of native_artifact_files
  .grabl/automation.yml
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  test/install.sh
Labels: type: build, type: refactor

#138 Fix test-deployment-npm
  .grabl/automation.yml
Labels: type: build

#137 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#140 RPC implementation for sending match aggregate, match group, and match group aggregate queries
  common/errors/ErrorMessage.ts
  concept/answer/Answer.ts
  concept/answer/ConceptMapGroup.ts
  concept/answer/Numeric.ts
  concept/answer/NumericGroup.ts
  dependencies/graknlabs/artifacts.bzl
  dependencies_internal.ts
  package-lock.json
  package.json
  query/QueryManager.ts
Labels: type: feature

#142 Bump year in license headers to 2021
  LICENSE
  dependencies/graknlabs/repositories.bzl
Labels: type: build

#143 Update automation.yml to include `release` dependencies
  .grabl/automation.yml
Labels: priority: high, type: bug

#147 Fix QueryManager's match methods
  query/QueryManager.ts
Labels: priority: high, type: bug

#149 Fix running matchAggregate queries
  concept/answer/Numeric.ts
  query/QueryManager.ts
Labels: priority: blocker, type: bug

#150 Finish implementing Concept BDD
  .grabl/automation.yml
  concept/thing/impl/ThingImpl.ts
  concept/type/ThingType.ts
  concept/type/impl/AttributeTypeImpl.ts
  concept/type/impl/ThingTypeImpl.ts
  concept/type/impl/TypeImpl.ts
  dependencies/graknlabs/repositories.bzl
  package-lock.json
  package.json
  rpc/Stream.ts
  test/behaviour/concept/thing/ThingSteps.ts
  test/behaviour/concept/thing/attribute/AttributeSteps.ts
  test/behaviour/concept/thing/entity/EntitySteps.ts
  test/behaviour/concept/thing/relation/RelationSteps.ts
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.ts
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/relationtype/RelationTypeSteps.ts
  test/behaviour/concept/type/thingtype/ThingTypeSteps.ts
  test/behaviour/config/Parameters.ts
  test/behaviour/connection/ConnectionSteps.ts
  test/behaviour/connection/session/SessionSteps.ts
  test/behaviour/connection/transaction/TransactionSteps.ts
  test/behaviour/cucumber_test.sh
  test/behaviour/graql/language/define/DefineSteps.ts
  test/behaviour/util/Util.ts
  test/integration/test-concept.js
Labels: priority: medium, type: feature

#152 Add ability to retrieve all rules
  BUILD
  dependencies_internal.ts
  logic/LogicManager.ts
  logic/Rule.ts
  logic/impl/RuleImpl.ts
  package-lock.json
  package.json
Labels: priority: medium, type: feature

#153 Fix console warnings caused by out of date dependency
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  package-lock.json
  package.json
Labels: type: bug

#154 Update dependencies and the version
  VERSION
  package.json
Labels: type: build

#155 Reenable remote build caching
  .bazelrc
  .grabl/automation.yml
Labels: type: build
