Repository vaticle/typedb-client-nodejs, pull requests merged in 2021-02, with the labels that each got.

#159 Refactor code to work with latest @graknlabs_dependencies
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#160 Use self-hosted Bazel cache
  .bazelrc
Labels: priority: high, type: build, type: feature

#161 Bump protocol to add option for inference tracing
  GraknOptions.ts
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  package-lock.json
  package.json
  test/BUILD
Labels: priority: high, type: feature
