Repository vaticle/typedb-client-nodejs, pull requests merged in 2022-01, with the labels that each got.

#198 Upgrade Bazel to v4.0.0
  .bazelrc
  .bazelversion
  WORKSPACE
  yarn.lock
Labels: type: build, priority: medium

#200 Upgrade dependencies
  dependencies/vaticle/repositories.bzl
Labels: dependencies

#201 Fix deployment failure due to wrong auth token
  .grabl/automation.yml
  dependencies/vaticle/repositories.bzl
Labels: type: build, priority: high

#202 Store error on transaction stream and clean up completed query state
  .grabl/automation.yml
  connection/TypeDBTransactionImpl.ts
  query/QueryManagerImpl.ts
  stream/BidirectionalStream.ts
  stream/ResponseCollector.ts
  stream/ResponsePartIterator.ts
Labels: type: refactor, priority: high

#203 Don't delete response collectors in a transaction
  .grabl/automation.yml
  VERSION
  api/connection/TypeDBTransaction.ts
  package.json
  stream/BidirectionalStream.ts
  stream/ResponsePartIterator.ts
  test/integration/test-stream.js
Labels: type: bug, priority: high
